### Bubble Sort

- time complexity = $O(n^2)$
- spalce complexity = $O(1)$

In [1]:
def bubblesort(arr):
    
    n = len(arr)
    
    for i in range(n-1, 0, -1): # set the "range" of each iteration
        
        for idx in range(i): # for each interation
            
            if arr[idx] > arr[idx + 1]: # check if the current element is larger than the next one 
                arr[idx], arr[idx+1] = arr[idx+1], arr[idx] # if yes, then swap the 2, moving the larger value to the left
    
    return arr

test = np.random.permutation(100)

bubblesort(test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Insertion Sort

- time complexity = $O(n^2)$
- space complexity = $O(1)$

In [2]:
def insertionsort (arr):
    
    for i in range(len(arr)):
        
        cursor = arr[i] # target element
        pos = i # position of the target element
        
        while pos > 0 and arr[pos-1] > cursor: # condition checks whether the target is smaller than the element before it
            
            arr[pos] = arr[pos - 1] # if yes, swap the target and the element before it
            
            pos = pos - 1 # move postion backward for 1
            
        arr[pos] = cursor # assign the target element to the new position
            
    return arr

test = np.random.permutation(100)

insertionsort(test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Selection Sort

- time complexity = $O(n^2)$
- space complexity = $O(1)$

In [3]:
def selectionsort(arr):
    
    for i in range(len(arr)):
        
        minimum = i # anchor the index of the left-most element to be the minimum
        
        for j in range(i+1, len(arr)): # iterate over elements to the left of the anchor, the unsorted part
            
            if arr[j] < arr[minimum]: # check if each element is smaller than the anchor
                minimum = j # if yes, update the anchor index, thus finding the smallest element in the left, unsorted part
                
        arr[minimum], arr[i] = arr[i], arr[minimum] # 
            
    return arr

test = np.random.permutation(100)

selectionsort(test)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Quick Sort
- time complexity = $O(nlog(n))$
- space complexity = $O(log(n))$

In [4]:
def quicksort(arr):
    n = len(arr)
    
    # define base case
    if n < 2:
        return arr
    
    # set intial partition frontier to be the 1st element
    current_idx = 0
    
    # start the loop from 2nd to nth element (the right side), the partition loop
    for i in range(1, n):
        # check if each value on the right side is smaller than the current pivot
        # if yes, move the frontier so that the larger value becomes the new frontier. if not do nothing
        if arr[i] <= arr[0]: 
            current_idx += 1 
            temp = arr[i]
            arr[i] = arr[current_idx]
            arr[current_idx] = temp
    
    # after loop, swap the pivot and the frontier
    temp = arr[0]
    arr[0] = arr[current_idx]
    arr[current_idx] = temp
    
    # recursively quick sort the left & right sides
    left = quicksort(arr[0:current_idx])
    right = quicksort(arr[current_idx+1:n])
    # combine both sides + pivot
    arr = np.concatenate([left, np.array([arr[current_idx]]), right], axis=0)
    return arr
    
test = np.random.permutation(100).tolist()

quicksort(test)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

### Merge Sort

- time complexity = $O(nlog(n)$)
- space complexity = $O(n)$

In [5]:
def mergesort(arr):
    
    # end condition for recursion
    if len(arr) <= 1:
        return arr
    
    # find the mid-point of the arr
    mid = len(arr) // 2
    
    left, right = mergesort(arr[:mid]), mergesort(arr[mid:])
    
    return merge(left, right, arr.copy())

def merge(left, right, merged):
    
    left_idx, right_idx = 0, 0
    
    while left_idx < len(left) and right_idx < len(right):
        
        if left[left_idx] <= right[right_idx]:
            merged[left_idx + right_idx] = left[left_idx]
            left_idx += 1
        else:
            merged[left_idx + right_idx] = right[right_idx]
            right_idx += 1
        
    for left_idx in range(left_idx, len(left)):
        merged[left_idx + right_idx] = left[left_idx]
    
    for right_idx in range(right_idx, len(right)):
        merged[left_idx + right_idx] = right[right_idx]

    return merged
        
test = np.random.permutation(100)


mergesort(test)
    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])