In [2]:
import torch

In [3]:
## load data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
cols = ['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'bk', 'lstat', 'medv']
df = pd.read_csv (url, header=None, names = cols, delim_whitespace=True)
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   ptratio      bk  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [4]:
X_tensor = torch.from_numpy(df.loc[:, ['rm', 'age']].values)
y_tensor = torch.from_numpy(df.medv.values ).unsqueeze(1)
X_tensor = X_tensor.to(torch.float32)
y_tensor = y_tensor.to(torch.float32)

In [5]:
X_mean = X_tensor.mean(0)
X_std = X_tensor.std(0)
X_tensor_norm = (X_tensor - X_mean) / X_std
X_tensor_norm = torch.cat((torch.ones(X_tensor.shape[0], 1), X_tensor_norm), dim=1)
X_tensor_norm

tensor([[ 1.0000,  0.4133, -0.1199],
        [ 1.0000,  0.1941,  0.3668],
        [ 1.0000,  1.2814, -0.2655],
        ...,
        [ 1.0000,  0.9840,  0.7967],
        [ 1.0000,  0.7250,  0.7363],
        [ 1.0000, -0.3624,  0.4343]])

In [6]:
theta = torch.rand((3, 1), requires_grad=True)

In [7]:
def loss_fn(X, y, theta):
    preds = torch.mm(X, theta)
    return ((y - preds)**2).sum() / (2. * X.shape[0])

In [8]:
def training_loop(n_iter, X, y, theta, lr=0.01):
    for epoch in range(1, n_iter+1):
        if theta.grad is not None:
            theta.grad.zero_()
            
        loss = loss_fn(X, y, theta)
        loss.backward()
        
        with torch.no_grad():
            theta -= lr * theta.grad
        
        if epoch % 100 == 0:
            print(f'Iteration {epoch}, loss = {loss}')   

In [9]:
training_loop(5000, X_tensor_norm, y_tensor, theta)

Iteration 100, loss = 55.213863372802734
Iteration 200, loss = 24.525840759277344
Iteration 300, loss = 20.456636428833008
Iteration 400, loss = 19.912134170532227
Iteration 500, loss = 19.83860969543457
Iteration 600, loss = 19.828588485717773
Iteration 700, loss = 19.827199935913086
Iteration 800, loss = 19.826995849609375
Iteration 900, loss = 19.82697296142578
Iteration 1000, loss = 19.82697296142578
Iteration 1100, loss = 19.82697105407715
Iteration 1200, loss = 19.826969146728516
Iteration 1300, loss = 19.82696533203125
Iteration 1400, loss = 19.82697105407715
Iteration 1500, loss = 19.826974868774414
Iteration 1600, loss = 19.826974868774414
Iteration 1700, loss = 19.826974868774414
Iteration 1800, loss = 19.826974868774414
Iteration 1900, loss = 19.826974868774414
Iteration 2000, loss = 19.826974868774414
Iteration 2100, loss = 19.826974868774414
Iteration 2200, loss = 19.826974868774414
Iteration 2300, loss = 19.826974868774414
Iteration 2400, loss = 19.826974868774414
Iterati

In [10]:
theta

tensor([[22.5327],
        [ 5.9031],
        [-2.0486]], requires_grad=True)

In [11]:
theta.grad

tensor([[-9.3910e-05],
        [-2.3809e-05],
        [-1.1709e-05]])