### Import Packages

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
plt.style.use('bmh')
%matplotlib inline

### Load data from UCI database

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'

cols = ['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'bk', 'lstat', 'medv']

df = pd.read_csv (url, header=None, names = cols, delim_whitespace=True)

df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   ptratio      bk  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

### Create input variable matrix X and dependent variant y

In [3]:
# take 'rm' & 'age' as inputs, 'medv' as dependent

X = df.loc[:, ['rm', 'age']].values
X = (X-X.mean(axis = 0)) / (X.max(axis = 0) - X.min(axis = 0)) # normalize
X = np.column_stack((np.ones(len(X)), X)) # append 1 for intercept
y = df.medv.values

### Codes for algorithm

In [4]:
# define gradient descent

def gradient_descent(X, y, theta, lr  = 0.001, n = 1000000):
    
    m = len(y)
    cost_history = np.zeros(n)
    theta_history = np.zeros([len(theta), n])
    
    for i in range(n):        
        
        loss = X.dot(theta) - y
        cost = np.sum(loss ** 2) / (2 * m)

        
        for j in range(len(theta)):
            
            theta[j] = theta[j] - lr * X[:, j].dot(loss) / m
            
            
        cost_history[i] = cost
        theta_history[:, i] = theta
        
    return theta, cost_history, theta_history

### Test Results

In [5]:
# analytic solution

best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
best

array([22.53280632, 43.84785241, -7.0666259 ])

In [6]:
# loss with best coeffs

np.sum(np.square((X.dot(best) - y))) / (len(y)*2)

19.826967729550837

In [7]:
t = np.array((1.,2.,3.))
t

array([1., 2., 3.])

In [8]:
theta_final, cost_hist, theta_hist = gradient_descent(X, y, t)

In [9]:
theta_final

array([22.53280632, 43.84785037, -7.06662619])

In [10]:
cost_hist

array([275.68870503, 275.22302311, 274.75826791, ...,  19.82696773,
        19.82696773,  19.82696773])

In [11]:
theta_hist.T

array([[ 1.02153281,  2.00085118,  2.99876405],
       [ 1.04304408,  2.00170232,  2.99752821],
       [ 1.06453384,  2.00255344,  2.99629248],
       ...,
       [22.53280632, 43.84785037, -7.06662619],
       [22.53280632, 43.84785037, -7.06662619],
       [22.53280632, 43.84785037, -7.06662619]])

In [12]:
# sklearn verification

lr = LinearRegression(fit_intercept=True)
lr.fit(X[:, 1:3], y)
lr.intercept_, lr.coef_

(22.532806324110677, array([43.84785241, -7.0666259 ]))